{% set name = "sober" %}
{% set python_min = "3.12.0" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sober-{{ version }}.tar.gz
  sha256: 4c57cf3e9648e64606ad432c3d10c55191dc6ea229a9db6b3466ad4c550fcd6d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - eppy-core >=0.5.63,<0.6.0
    - numpy ==2.*
    - psutil ==6.*
    - pymoo >=0.6.1,<0.7.0
    - scipy >=1.13,<2.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - sober

about:
  home: https://github.com/airallergy/sober
  summary: sober optimises built environment robustly
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - airallergy
